/*
  FILE....: H_464_232.h

  Static arrays for LDPC codec H_464_232, generated by ldpc_gen_c_h_file.m.
*/

#define H_464_232_NUMBERPARITYBITS 232
#define H_464_232_MAX_ROW_WEIGHT 7
#define H_464_232_CODELENGTH 696
#define H_464_232_NUMBERROWSHCOLS 464
#define H_464_232_MAX_COL_WEIGHT 4
#define H_464_232_DEC_TYPE 0
#define H_464_232_MAX_ITER 100

extern const uint16_t H_464_232_H_rows[];
extern const uint16_t H_464_232_H_cols[];
extern const float H_464_232_input[];
extern const char H_464_232_detected_data[];

